name: tracker-gpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit
  - pip:
    - tensorflow-gpu
    - lxml
    - tqdm
    - seaborn
    - pillow
